#ifndef GORE_COLORS_H_INCLUDED
#define GORE_COLORS_H_INCLUDED

#include "joy_types.h"
#include "joy_math.h"
#include "joy_memory.h"

inline v4 ColorFrom255(int R, int G, int B) {
	float oneOver255 = 1.0f / 255.0f;
	v4 res = V4(R, G, B, 1.0f);
	res.r *= oneOver255;
	res.g *= oneOver255;
	res.b *= oneOver255;
    
    res.r = Clamp01(res.r);
    res.g = Clamp01(res.g);
    res.b = Clamp01(res.b);
    
	return(res);
}

inline int IntFromHexCharForColors(char C) {
	int res = 0;
    
	if (C >= 'a' && C <= 'f') {
		C += 'A' - 'a';
	}
    
	if (C >= '0' && C <= '9') {
		res = C - '0';
	}
    
	if (C >= 'A' && C <= 'F') {
		res = C + 10 - 'A';
	}
    
	return(res);
}

inline v4 ColorFromHex(char* str) {
	float oneOver255 = 1.0f / 255.0f;
    
	v4 res;
    
	Assert(str[0] == '#');
    
	int R, G, B;
	R = IntFromHexCharForColors(str[1]) * 16 + IntFromHexCharForColors(str[2]);
	G = IntFromHexCharForColors(str[3]) * 16 + IntFromHexCharForColors(str[4]);
	B = IntFromHexCharForColors(str[5]) * 16 + IntFromHexCharForColors(str[6]);
    
	res = V4(R, G, B, 1.0f);
    
	res.r *= oneOver255;
	res.g *= oneOver255;
	res.b *= oneOver255;
    
	return(res);
}

struct Color_Slot {
	v4 color;
	u32 colorU32;
	char* name;
};

enum ColorTableType {
	Color_Black,
	Color_White,
	Color_Red,
	Color_Green,
	Color_Blue,
	Color_Yellow,
	Color_Magenta,
	Color_Cyan,
	Color_PrettyBlue,
	Color_Purple,
	Color_Orange,
	Color_Brown,
	Color_Amber,
	Color_Burlywood,
	Color_DarkGoldenrod,
	Color_OliveDrab,
    Color_ToxicGreen,
    
    Color_Thistle,
    Color_Plum,
    Color_Violet,
    Color_Orchid,
    Color_Fuchsia,
    Color_MediumOrchid,
    Color_MediumPurple,
    Color_BlueViolet,
    Color_DarkViolet,
    Color_DarkOrchid,
    Color_DarkMagenta,
    Color_Indigo,
    Color_SlateBlue,
    Color_DarkSlateBlue,
    Color_Wine,
    
    Color_UltraViolet,
    Color_NeoMint,
    Color_BurntOrange,
    Color_Preview,
    Color_Obsidian,
    Color_MayaBlue,
    Color_MidnightBlue,
    Color_WhiteFA,
    Color_TitanWhite,
    Color_Haiti,
    
	ColorExt_AliceBlue,
	ColorExt_AntiqueWhite,
	ColorExt_AntiqueWhite1,
	ColorExt_AntiqueWhite2,
	ColorExt_AntiqueWhite3,
	ColorExt_AntiqueWhite4,
	ColorExt_aquamarine1,
	ColorExt_aquamarine2,
	ColorExt_aquamarine4,
	ColorExt_azure1,
	ColorExt_azure2,
	ColorExt_azure3,
	ColorExt_azure4,
	ColorExt_beige,
	ColorExt_bisque1,
	ColorExt_bisque2,
	ColorExt_bisque3,
	ColorExt_bisque4,
	ColorExt_black,
	ColorExt_BlanchedAlmond,
	ColorExt_blue1,
	ColorExt_blue2,
	ColorExt_blue4,
	ColorExt_BlueViolet,
	ColorExt_brown,
	ColorExt_brown1,
	ColorExt_brown2,
	ColorExt_brown3,
	ColorExt_brown4,
	ColorExt_burlywood,
	ColorExt_burlywood1,
	ColorExt_burlywood2,
	ColorExt_burlywood3,
	ColorExt_burlywood4,
	ColorExt_CadetBlue,
	ColorExt_CadetBlue1,
	ColorExt_CadetBlue2,
	ColorExt_CadetBlue3,
	ColorExt_CadetBlue4,
	ColorExt_chartreuse1,
	ColorExt_chartreuse2,
	ColorExt_chartreuse3,
	ColorExt_chartreuse4,
	ColorExt_chocolate,
	ColorExt_chocolate1,
	ColorExt_chocolate2,
	ColorExt_chocolate3,
	ColorExt_coral,
	ColorExt_coral1,
	ColorExt_coral2,
	ColorExt_coral3,
	ColorExt_coral4,
	ColorExt_CornflowerBlue,
	ColorExt_cornsilk1,
	ColorExt_cornsilk2,
	ColorExt_cornsilk3,
	ColorExt_cornsilk4,
	ColorExt_cyan1,
	ColorExt_cyan2,
	ColorExt_cyan3,
	ColorExt_cyan4,
	ColorExt_DarkGoldenrod,
	ColorExt_DarkGoldenrod1,
	ColorExt_DarkGoldenrod2,
	ColorExt_DarkGoldenrod3,
	ColorExt_DarkGoldenrod4,
	ColorExt_DarkGreen,
	ColorExt_DarkKhaki,
	ColorExt_DarkOliveGreen,
	ColorExt_DarkOliveGreen1,
	ColorExt_DarkOliveGreen2,
	ColorExt_DarkOliveGreen3,
	ColorExt_DarkOliveGreen4,
	ColorExt_DarkOrange,
	ColorExt_DarkOrange1,
	ColorExt_DarkOrange2,
	ColorExt_DarkOrange3,
	ColorExt_DarkOrange4,
	ColorExt_DarkOrchid,
	ColorExt_DarkOrchid1,
	ColorExt_DarkOrchid2,
	ColorExt_DarkOrchid3,
	ColorExt_DarkOrchid4,
	ColorExt_DarkSalmon,
	ColorExt_DarkSeaGreen,
	ColorExt_DarkSeaGreen1,
	ColorExt_DarkSeaGreen2,
	ColorExt_DarkSeaGreen3,
	ColorExt_DarkSeaGreen4,
	ColorExt_DarkSlateBlue,
	ColorExt_DarkSlateGray,
	ColorExt_DarkSlateGray1,
	ColorExt_DarkSlateGray2,
	ColorExt_DarkSlateGray3,
	ColorExt_DarkSlateGray4,
	ColorExt_DarkTurquoise,
	ColorExt_DarkViolet,
	ColorExt_DeepPink1,
	ColorExt_DeepPink2,
	ColorExt_DeepPink3,
	ColorExt_DeepPink4,
	ColorExt_DeepSkyBlue1,
	ColorExt_DeepSkyBlue2,
	ColorExt_DeepSkyBlue3,
	ColorExt_DeepSkyBlue4,
	ColorExt_DimGray,
	ColorExt_DodgerBlue1,
	ColorExt_DodgerBlue2,
	ColorExt_DodgerBlue3,
	ColorExt_DodgerBlue4,
	ColorExt_firebrick,
	ColorExt_firebrick1,
	ColorExt_firebrick2,
	ColorExt_firebrick3,
	ColorExt_firebrick4,
	ColorExt_FloralWhite,
	ColorExt_ForestGreen,
	ColorExt_gainsboro,
	ColorExt_GhostWhite,
	ColorExt_gold1,
	ColorExt_gold2,
	ColorExt_gold3,
	ColorExt_gold4,
	ColorExt_goldenrod,
	ColorExt_goldenrod1,
	ColorExt_goldenrod2,
	ColorExt_goldenrod3,
	ColorExt_goldenrod4,
	ColorExt_gray,
	ColorExt_gray1,
	ColorExt_gray2,
	ColorExt_gray3,
	ColorExt_gray4,
	ColorExt_gray5,
	ColorExt_gray6,
	ColorExt_gray7,
	ColorExt_gray8,
	ColorExt_gray9,
	ColorExt_gray10,
	ColorExt_gray11,
	ColorExt_gray12,
	ColorExt_gray13,
	ColorExt_gray14,
	ColorExt_gray15,
	ColorExt_gray16,
	ColorExt_gray17,
	ColorExt_gray18,
	ColorExt_gray19,
	ColorExt_gray20,
	ColorExt_gray21,
	ColorExt_gray22,
	ColorExt_gray23,
	ColorExt_gray24,
	ColorExt_gray25,
	ColorExt_gray26,
	ColorExt_gray27,
	ColorExt_gray28,
	ColorExt_gray29,
	ColorExt_gray30,
	ColorExt_gray31,
	ColorExt_gray32,
	ColorExt_gray33,
	ColorExt_gray34,
	ColorExt_gray35,
	ColorExt_gray36,
	ColorExt_gray37,
	ColorExt_gray38,
	ColorExt_gray39,
	ColorExt_gray40,
	ColorExt_gray41,
	ColorExt_gray42,
	ColorExt_gray43,
	ColorExt_gray44,
	ColorExt_gray45,
	ColorExt_gray46,
	ColorExt_gray47,
	ColorExt_gray48,
	ColorExt_gray49,
	ColorExt_gray50,
	ColorExt_gray51,
	ColorExt_gray52,
	ColorExt_gray53,
	ColorExt_gray54,
	ColorExt_gray55,
	ColorExt_gray56,
	ColorExt_gray57,
	ColorExt_gray58,
	ColorExt_gray59,
	ColorExt_gray60,
	ColorExt_gray61,
	ColorExt_gray62,
	ColorExt_gray63,
	ColorExt_gray64,
	ColorExt_gray65,
	ColorExt_gray66,
	ColorExt_gray67,
	ColorExt_gray68,
	ColorExt_gray69,
	ColorExt_gray70,
	ColorExt_gray71,
	ColorExt_gray72,
	ColorExt_gray73,
	ColorExt_gray74,
	ColorExt_gray75,
	ColorExt_gray76,
	ColorExt_gray77,
	ColorExt_gray78,
	ColorExt_gray79,
	ColorExt_gray80,
	ColorExt_gray81,
	ColorExt_gray82,
	ColorExt_gray83,
	ColorExt_gray84,
	ColorExt_gray85,
	ColorExt_gray86,
	ColorExt_gray87,
	ColorExt_gray88,
	ColorExt_gray89,
	ColorExt_gray90,
	ColorExt_gray91,
	ColorExt_gray92,
	ColorExt_gray93,
	ColorExt_gray94,
	ColorExt_gray95,
	ColorExt_gray97,
	ColorExt_gray98,
	ColorExt_gray99,
	ColorExt_green1,
	ColorExt_green2,
	ColorExt_green3,
	ColorExt_green4,
	ColorExt_GreenYellow,
	ColorExt_honeydew1,
	ColorExt_honeydew2,
	ColorExt_honeydew3,
	ColorExt_honeydew4,
	ColorExt_HotPink,
	ColorExt_HotPink1,
	ColorExt_HotPink2,
	ColorExt_HotPink3,
	ColorExt_HotPink4,
	ColorExt_IndianRed,
	ColorExt_IndianRed1,
	ColorExt_IndianRed2,
	ColorExt_IndianRed3,
	ColorExt_IndianRed4,
	ColorExt_ivory1,
	ColorExt_ivory2,
	ColorExt_ivory3,
	ColorExt_ivory4,
	ColorExt_khaki,
	ColorExt_khaki1,
	ColorExt_khaki2,
	ColorExt_khaki3,
	ColorExt_khaki4,
	ColorExt_lavender,
	ColorExt_LavenderBlush1,
	ColorExt_LavenderBlush2,
	ColorExt_LavenderBlush3,
	ColorExt_LavenderBlush4,
	ColorExt_LawnGreen,
	ColorExt_LemonChiffon1,
	ColorExt_LemonChiffon2,
	ColorExt_LemonChiffon3,
	ColorExt_LemonChiffon4,
	ColorExt_light,
	ColorExt_LightBlue,
	ColorExt_LightBlue1,
	ColorExt_LightBlue2,
	ColorExt_LightBlue3,
	ColorExt_LightBlue4,
	ColorExt_LightCoral,
	ColorExt_LightCyan1,
	ColorExt_LightCyan2,
	ColorExt_LightCyan3,
	ColorExt_LightCyan4,
	ColorExt_LightGoldenrod1,
	ColorExt_LightGoldenrod2,
	ColorExt_LightGoldenrod3,
	ColorExt_LightGoldenrod4,
	ColorExt_LightGoldenrodYellow,
	ColorExt_LightGray,
	ColorExt_LightPink,
	ColorExt_LightPink1,
	ColorExt_LightPink2,
	ColorExt_LightPink3,
	ColorExt_LightPink4,
	ColorExt_LightSalmon1,
	ColorExt_LightSalmon2,
	ColorExt_LightSalmon3,
	ColorExt_LightSalmon4,
	ColorExt_LightSeaGreen,
	ColorExt_LightSkyBlue,
	ColorExt_LightSkyBlue1,
	ColorExt_LightSkyBlue2,
	ColorExt_LightSkyBlue3,
	ColorExt_LightSkyBlue4,
	ColorExt_LightSlateBlue,
	ColorExt_LightSlateGray,
	ColorExt_LightSteelBlue,
	ColorExt_LightSteelBlue1,
	ColorExt_LightSteelBlue2,
	ColorExt_LightSteelBlue3,
	ColorExt_LightSteelBlue4,
	ColorExt_LightYellow1,
	ColorExt_LightYellow2,
	ColorExt_LightYellow3,
	ColorExt_LightYellow4,
	ColorExt_LimeGreen,
	ColorExt_linen,
	ColorExt_magenta,
	ColorExt_magenta2,
	ColorExt_magenta3,
	ColorExt_magenta4,
	ColorExt_maroon,
	ColorExt_maroon1,
	ColorExt_maroon2,
	ColorExt_maroon3,
	ColorExt_maroon4,
	ColorExt_medium,
	ColorExt_MediumAquamarine,
	ColorExt_MediumBlue,
	ColorExt_MediumOrchid,
	ColorExt_MediumOrchid1,
	ColorExt_MediumOrchid2,
	ColorExt_MediumOrchid3,
	ColorExt_MediumOrchid4,
	ColorExt_MediumPurple,
	ColorExt_MediumPurple1,
	ColorExt_MediumPurple2,
	ColorExt_MediumPurple3,
	ColorExt_MediumPurple4,
	ColorExt_MediumSeaGreen,
	ColorExt_MediumSlateBlue,
	ColorExt_MediumSpringGreen,
	ColorExt_MediumTurquoise,
	ColorExt_MediumVioletRed,
	ColorExt_MidnightBlue,
	ColorExt_MintCream,
	ColorExt_MistyRose1,
	ColorExt_MistyRose2,
	ColorExt_MistyRose3,
	ColorExt_MistyRose4,
	ColorExt_moccasin,
	ColorExt_NavajoWhite1,
	ColorExt_NavajoWhite2,
	ColorExt_NavajoWhite3,
	ColorExt_NavajoWhite4,
	ColorExt_NavyBlue,
	ColorExt_OldLace,
	ColorExt_OliveDrab,
	ColorExt_OliveDrab1,
	ColorExt_OliveDrab2,
	ColorExt_OliveDrab4,
	ColorExt_orange1,
	ColorExt_orange2,
	ColorExt_orange3,
	ColorExt_orange4,
	ColorExt_OrangeRed1,
	ColorExt_OrangeRed2,
	ColorExt_OrangeRed3,
	ColorExt_OrangeRed4,
	ColorExt_orchid,
	ColorExt_orchid1,
	ColorExt_orchid2,
	ColorExt_orchid3,
	ColorExt_orchid4,
	ColorExt_pale,
	ColorExt_PaleGoldenrod,
	ColorExt_PaleGreen,
	ColorExt_PaleGreen1,
	ColorExt_PaleGreen2,
	ColorExt_PaleGreen3,
	ColorExt_PaleGreen4,
	ColorExt_PaleTurquoise,
	ColorExt_PaleTurquoise1,
	ColorExt_PaleTurquoise2,
	ColorExt_PaleTurquoise3,
	ColorExt_PaleTurquoise4,
	ColorExt_PaleVioletRed,
	ColorExt_PaleVioletRed1,
	ColorExt_PaleVioletRed2,
	ColorExt_PaleVioletRed3,
	ColorExt_PaleVioletRed4,
	ColorExt_PapayaWhip,
	ColorExt_PeachPuff1,
	ColorExt_PeachPuff2,
	ColorExt_PeachPuff3,
	ColorExt_PeachPuff4,
	ColorExt_pink,
	ColorExt_pink1,
	ColorExt_pink2,
	ColorExt_pink3,
	ColorExt_pink4,
	ColorExt_plum,
	ColorExt_plum1,
	ColorExt_plum2,
	ColorExt_plum3,
	ColorExt_plum4,
	ColorExt_PowderBlue,
	ColorExt_purple,
	ColorExt_rebeccapurple,
	ColorExt_purple1,
	ColorExt_purple2,
	ColorExt_purple3,
	ColorExt_purple4,
	ColorExt_red1,
	ColorExt_red2,
	ColorExt_red3,
	ColorExt_red4,
	ColorExt_RosyBrown,
	ColorExt_RosyBrown1,
	ColorExt_RosyBrown2,
	ColorExt_RosyBrown3,
	ColorExt_RosyBrown4,
	ColorExt_RoyalBlue,
	ColorExt_RoyalBlue1,
	ColorExt_RoyalBlue2,
	ColorExt_RoyalBlue3,
	ColorExt_RoyalBlue4,
	ColorExt_SaddleBrown,
	ColorExt_salmon,
	ColorExt_salmon1,
	ColorExt_salmon2,
	ColorExt_salmon3,
	ColorExt_salmon4,
	ColorExt_SandyBrown,
	ColorExt_SeaGreen1,
	ColorExt_SeaGreen2,
	ColorExt_SeaGreen3,
	ColorExt_SeaGreen4,
	ColorExt_seashell1,
	ColorExt_seashell2,
	ColorExt_seashell3,
	ColorExt_seashell4,
	ColorExt_sienna,
	ColorExt_sienna1,
	ColorExt_sienna2,
	ColorExt_sienna3,
	ColorExt_sienna4,
	ColorExt_SkyBlue,
	ColorExt_SkyBlue1,
	ColorExt_SkyBlue2,
	ColorExt_SkyBlue3,
	ColorExt_SkyBlue4,
	ColorExt_SlateBlue,
	ColorExt_SlateBlue1,
	ColorExt_SlateBlue2,
	ColorExt_SlateBlue3,
	ColorExt_SlateBlue4,
	ColorExt_SlateGray,
	ColorExt_SlateGray1,
	ColorExt_SlateGray2,
	ColorExt_SlateGray3,
	ColorExt_SlateGray4,
	ColorExt_snow1,
	ColorExt_snow2,
	ColorExt_snow3,
	ColorExt_snow4,
	ColorExt_SpringGreen1,
	ColorExt_SpringGreen2,
	ColorExt_SpringGreen3,
	ColorExt_SpringGreen4,
	ColorExt_SteelBlue,
	ColorExt_SteelBlue1,
	ColorExt_SteelBlue2,
	ColorExt_SteelBlue3,
	ColorExt_SteelBlue4,
	ColorExt_tan,
	ColorExt_tan1,
	ColorExt_tan2,
	ColorExt_tan3,
	ColorExt_tan4,
	ColorExt_thistle,
	ColorExt_thistle1,
	ColorExt_thistle2,
	ColorExt_thistle3,
	ColorExt_thistle4,
	ColorExt_tomato1,
	ColorExt_tomato2,
	ColorExt_tomato3,
	ColorExt_tomato4,
	ColorExt_turquoise,
	ColorExt_turquoise1,
	ColorExt_turquoise2,
	ColorExt_turquoise3,
	ColorExt_turquoise4,
	ColorExt_violet,
	ColorExt_VioletRed,
	ColorExt_VioletRed1,
	ColorExt_VioletRed2,
	ColorExt_VioletRed3,
	ColorExt_VioletRed4,
	ColorExt_wheat,
	ColorExt_wheat1,
	ColorExt_wheat2,
	ColorExt_wheat3,
	ColorExt_wheat4,
	ColorExt_white,
	ColorExt_WhiteSmoke,
	ColorExt_yellow1,
	ColorExt_yellow2,
	ColorExt_yellow3,
	ColorExt_yellow4,
	ColorExt_YellowGreen,
    
	Color_Count,
};

// TODO(Dima): ZII memory region here
// TODO(Dima): Organize like hash table nearby
struct Color_State{
	mem_arena* colorsMem;
    Color_Slot colorTable[Color_Count];
};

inline v4 GetColor(Color_State* colorState, u32 colorIndex) {
	v4 result = colorState->colorTable[colorIndex].color;
    
	return(result);
}

//NOTE(dima): Function prototypes
void InitColorsState(Color_State* state, mem_arena* colorsMemory);

#endif